### ISSUE TITLE
Observations

### ISSUE THREAD

**Issue by nnamdei** [dbytecoderc/sendit-api#9]
Nice job with the work so far. A few observation that needs clarification. 

- How Do you differentiate dispatch riders in the user table 
- How does one resolve pricing for each parcel or did you name it as "quote" @dbytecoderc

**Comment by dbytecoderc** [comment]
Hello @nnamdei,
- To answer your first question I plan to add a service module functionality where the third party dispatch service companies would be able to signup, in that regard as soon as a user creates an order a service provider would be randomly assigned to that user, this service provider can be changed at the request of the user.
- Secondly, I want to make the quote and pricing API unopinionated, the prices would be calculated on the frontend based on the weight of the parcels inputted by the user in real-time to create a good user experience.

**Comment by nnamdei** [comment]
Thanks for the reply and in a use case where there is no third party dispatch company how will the system be put in shape to cope with that requirement. for instance, company a has dispatch riders has no need for a third party.

Secondly, how would the real time tracking work in a real life situation based on your model for tracking.

**Comment by dbytecoderc** [comment]
- At the moment this app is mainly a B to C application which means whoever owns and operates the application would handle all logistical implications of moving a parcel across locations and would only need to refer to service companies for the current location of the order being delivered, if a company has dispatch riders then they won't have the need for this application. I hope to add a B to B interface where companies with resident dispatch services can use the platform as a tool for analytics.

- Secondly, during the creation of delivery orders geolocation APIs would be used to validate addresses on the frontend before they are sent to the backend, and I would also leverage a distance matrix service to display the distance between the current location and the destination, which would also display GUIs indicating the pickup location, current location, and destination.
